IF (OBJECT_ID('TABELA_TESTE') IS NOT NULL) DROP TABLE TABELA_TESTE 
BEGIN
	CREATE TABLE TABELA_TESTE 
	(
		ID        INT, 
		DESCRICAO VARCHAR(100)
	) 
END 

SELECT * FROM TABELA_TESTE WITH (READPAST)