
DECLARE @NUMERO INT = ROUND(RAND() * 10, 2) 

SELECT COALESCE(
	(
		CASE @NUMERO 
			WHEN 1 THEN 'UM'
			WHEN 2 THEN 'DOIS'
			WHEN 3 THEN 'TRÊS'
			WHEN 4 THEN 'QUATRO'
			WHEN 5 THEN 'CINCO'
			WHEN 6 THEN 'SEIS'
			WHEN 7 THEN 'SETE'
			WHEN 8 THEN 'OITO'
			WHEN 9 THEN 'NOVE'
			WHEN 10 THEN 'DEZ'
			WHEN 11 THEN 'ONZE'
			WHEN 12 THEN 'DOZE' 
		END
	), 'NÚMERO NÃO ENCONTRADO ' + CONVERT(VARCHAR(2), @NUMERO))