CREATE DATABASE DB_TESTE
GO 

USE DB_TESTE
GO

/*
	DELIMITAÇÃO DA SITUAÇÃO:

	TABELA COM HISTÓRICO DE TRANSACIONAL E É NECESSÁRIO EXIBIR INFORMAÇÕES DO MÊS ATUAL EM COMPARAÇÃO COM O MÊS PASSADO (D -30) 

	OBSERVAÇÃO: A CHAVE DESTA TABELA TABELA_FATO É A DATA DO ANO NO FORMATO yyyymmdd

*/

-- ==========================
-- ESTRUTURA DE TESTE DA FATO 
-- ========================== 
IF NOT EXISTS (SELECT 1 FROM SYS.all_objects WHERE TYPE = 'U' AND NAME = 'TABELA_FATO')
BEGIN
CREATE TABLE TABELA_FATO 
(
	PK_DATA INT, 
	INFORMACAO_UM VARCHAR(100), 
	INFORMACAO_DOIS VARCHAR(100), 
	VALOR_MES INT

)
END
-- =========================
-- PARA PREENCHER A TABELA
-- =========================

	
INSERT INTO TABELA_FATO 
	VALUES 
	(20190101, 'INFORMACAO 1', 'INFORMACAO 2 ', 23203),
	(20190201, 'INFORMACAO 1', 'INFORMACAO 2 ', 24203),
	(20190301, 'INFORMACAO 1', 'INFORMACAO 2 ', 26203),
	(20190401, 'INFORMACAO 1', 'INFORMACAO 2 ', 21203),
	(20190501, 'INFORMACAO 1', 'INFORMACAO 2 ', 28203)


--
-- RESOLVENDO A SITUAÇÃO (AO MENOS TENTANDO)
--	

DECLARE 
	@ANO_MES CHAR(6) = CONVERT(CHAR(6), GETDATE(), 112)

SELECT *,LEFT(CONVERT(VARCHAR, PK_DATA),6) AS COL_MES
INTO #TMP_TABELA_FATO
FROM TABELA_FATO 


SELECT 
* 
FROM #TMP_TABELA_FATO 
WHERE COL_MES = @ANO_MES




