
--CREATE TABLE TMP_DIMENSAOTEMPO 
--(
--	ID_DATA INT NOT NULL,
--	NU_ANO  SMALLINT NOT NULL, 
--	NU_MES TINYINT NOT NULL,
--	NU_DIA TINYINT NOT NULL,
--	NO_MES VARCHAR(12) NOT NULL, 
--	SG_MES VARCHAR(3) NOT NULL, 
--	DIA_SEMANA VARCHAR(15) NOT NULL,
--	SG_SEMANA VARCHAR(3) NOT NULL

--	PRIMARY KEY (ID_DATA)
--)

DECLARE @CONT INT = 0

DECLARE 
	@DATA_INICIAL DATE = '1970-01-03'


WHILE @CONT < 29219
BEGIN

	
INSERT INTO TMP_DIMENSAOTEMPO 
SELECT 
	CONVERT(INT, FORMAT(@DATA_INICIAL,'yyyymmdd')) AS ID_DATA,
	YEAR(@DATA_INICIAL)     AS NU_ANO,
	MONTH(@DATA_INICIAL)    AS NU_MES, 
	DAY(@DATA_INICIAL)      AS NU_DIA,
	UPPER(FORMAT(@DATA_INICIAL, 'MMMM'))   AS NO_MES,
	UPPER(FORMAT(@DATA_INICIAL, 'MMM'))    AS SG_MES,
	UPPER(FORMAT(@DATA_INICIAL, 'dddd'))   AS DIA_SEMANA,
	UPPER(FORMAT(@DATA_INICIAL, 'ddd'))    AS SG_SEMANA

	SET @DATA_INICIAL = DATEADD(DAY, @CONT, @DATA_INICIAL)
	
	 SET @CONT = @CONT + 1 
END 

SELECT * FROM TMP_DIMENSAOTEMPO