
USE DB_TESTE
GO


IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TMP_DIMENSAOTEMPO')
	BEGIN 
	CREATE TABLE TMP_DIMENSAOTEMPO 
	 (
 		ID_DATA INT NOT NULL,
 		NU_ANO  SMALLINT NOT NULL, 
 		NU_MES TINYINT NOT NULL,
 		NU_DIA TINYINT NOT NULL,
 		NO_MES VARCHAR(12) NOT NULL, 
 		SG_MES VARCHAR(3) NOT NULL, 
 		DIA_SEMANA VARCHAR(15) NOT NULL,
 		SG_SEMANA VARCHAR(3) NOT NULL

 		PRIMARY KEY (ID_DATA)
	 )
	END
GO

DECLARE 
	  @DATA_INICIAL DATE = '1900-01-03'
	 ,@DATA_SAIDA DATE,
	  @CONT INT = 1

WHILE @CONT < 200000
BEGIN
	

	SET @DATA_SAIDA  =  DATEADD(DAY, @CONT, @DATA_INICIAL)

	INSERT INTO TMP_DIMENSAOTEMPO
	SELECT 
		CONVERT(INT, FORMAT(@DATA_SAIDA,'yyyyMMdd')) AS ID_DATA,
		YEAR(@DATA_SAIDA)     AS NU_ANO,
		MONTH(@DATA_SAIDA)    AS NU_MES, 
		DAY(@DATA_SAIDA)      AS NU_DIA,
		UPPER(FORMAT(@DATA_SAIDA, 'MMMM'))   AS NO_MES,
		UPPER(FORMAT(@DATA_SAIDA, 'MMM'))    AS SG_MES,
		UPPER(FORMAT(@DATA_SAIDA, 'dddd'))   AS DIA_SEMANA,
		UPPER(FORMAT(@DATA_SAIDA, 'ddd'))    AS SG_SEMANA



	SET @CONT += 1 

END 
GO

SELECT * FROM TMP_DIMENSAOTEMPO
--GO

