

--SELECT SUM(FATO.VR_ITEM) 
--FROM ACA.ACATF009_INDCE_EFCNA_OPRCL FATO
--INNER JOIN DIM.DIMTD005_PERIODO PERIODO ON (FATO.NU_IDNTR_PERIODO = PERIODO.NU_IDNTR_PERIODO)


SELECT 
	SUM(FATO.VR_ITEM)
FROM ACA.ACATF009_INDCE_EFCNA_OPRCL FATO
INNER JOIN DIM.DIMTD005_PERIODO PERIODO ON (FATO.NU_IDNTR_PERIODO = PERIODO.NU_IDNTR_PERIODO)
WHERE PERIODO.DT_PERIODO BETWEEN  DATEADD(MONTH, -11, '2019-01-01 00:00:00.000') AND '2019-01-01 00:00:00.000'  



SELECT 
	--DISTINCT
	--(
	--	SELECT 
	--		SUM(FATO.VR_ITEM)
	--	FROM 
	--	ACA.ACATF009_INDCE_EFCNA_OPRCL FATO 
	--	INNER JOIN DIM.DIMTD005_PERIODO PERIODO ON (FATO.NU_IDNTR_PERIODO = PERIODO.NU_IDNTR_PERIODO)
	--	WHERE PERIODO.DT_PERIODO BETWEEN DATAS.DATA_RETROATIVA AND DATAS.DATA_PERIODO_COMPLETO
		
	--) AS SOMA_PERIODO,
	-- DATAS.DATA_PERIODO_COMPLETO AS INICIO_PERIODO
	--,DATAS.DATA_RETROATIVA       AS FINAL_PERIODO 
	*
	 
FROM ACA.ACATF009_INDCE_EFCNA_OPRCL FATO

INNER JOIN 
(
	SELECT DISTINCT 
		FATO.NU_IDNTR_PERIODO       AS ID_PERIODO_COMPLETO,
		PERIODO_COMPLETO.DT_PERIODO AS DATA_PERIODO_COMPLETO,
		DATEADD(MONTH, -11, PERIODO_COMPLETO.DT_PERIODO) AS DATA_RETROATIVA
	FROM 
		ACA.ACATF009_INDCE_EFCNA_OPRCL FATO
	INNER JOIN DIM.DIMTD005_PERIODO PERIODO_COMPLETO ON (FATO.NU_IDNTR_PERIODO = PERIODO_COMPLETO.NU_IDNTR_PERIODO)

) DATAS ON (FATO.NU_IDNTR_PERIODO = DATAS.ID_PERIODO_COMPLETO)


