IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TABELA_TESTE')
BEGIN
	DROP TABLE TABELA_TESTE  
END 
GO 

CREATE TABLE TABELA_TESTE 
(
	ID     INT IDENTITY(1, 1),
	DESCRI VARCHAR(20)

	PRIMARY KEY (ID)
)
GO 


INSERT INTO TABELA_TESTE (DESCRI)	
	VALUES ('TESTE1'), ('TESTE2'), ('TESTE3'), ('TESTE4')
GO 25


SELECT * FROM TABELA_TESTE



SET IDENTITY_INSERT TABELA_TESTE ON
	INSERT INTO TABELA_TESTE (ID, DESCRI) VALUES (-1, 'NAO INFORMADO')
	INSERT INTO TABELA_TESTE (ID, DESCRI) VALUES (-2, 'NAO CADASTRADO')
	INSERT INTO TABELA_TESTE (ID, DESCRI) VALUES (-3, 'NAO SE APLICA')
SET IDENTITY_INSERT TABELA_TESTE OFF



SELECT * FROM TABELA_TESTE